### PR TITLE
4 add can support

### PR DESCRIPTION
**Pull request by andreaskuster**

### CODE REVIEW

**Comment by KarlSchu** [comment]
@andreaskuster Whats the matter with this PR?

**Comment by andreaskuster** [comment]
@garned Please fix the conflicts and request a review.

**Comment by andreaskuster** [comment]
I fixed the obivous issue with duplicate object instances, and run the formatting script, however, I encourage you to resolve the compilation issues before re-requesting a review. 
The code formatting can be run using the script `extras/format.sh`

**Comment by andreaskuster** [comment]
Resolve rebase in #131

**Pull request closed without merging**
