### PR TITLE
WIP: Add captive auto login

### PR DESCRIPTION
**Pull request by andreaskuster**

### CODE REVIEW

**Comment by andreaskuster** [comment]
see #67

**Review by KarlSchu — APPROVED** [review]

**Comment by andreaskuster** [comment]
@KarlSchu Thanks for approving it, but this PR needs the adjustment from my template swisspass login to the captive portal login at BUZ :)

**Comment by KarlSchu** [comment]
:) of course, I'll do it tomorrow.

**Comment by andreaskuster** [comment]
@KarlSchu Does this work now at BUZ?

**Pull request merged**
